# Generated by Django 4.2 on 2023-08-22 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Docteurs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullname", models.CharField(max_length=30)),
                ("age", models.IntegerField()),
                (
                    "sexe",
                    models.CharField(
                        choices=[("H", "Homme"), ("F", "Femme")], max_length=1
                    ),
                ),
                ("telephone", models.IntegerField()),
                ("comment", models.TextField()),
                ("image", models.ImageField(upload_to="photos/%d/%m/%y")),
                ("specialitesmedicales", models.TextField()),
                ("Anneesdepratique", models.DateField()),
                ("Certificationsprofessionnelles", models.CharField(max_length=200)),
            ],
        ),
    ]
