# Generated by Django 4.2 on 2023-08-29 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medecins", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sicks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lst_maladie",
                    models.CharField(
                        choices=[
                            ("Acné", "Acné"),
                            ("Alopécie", "Alopécie"),
                            ("Amyloïdose", "Amyloïdose"),
                            ("Angiodermite", "Angiodermite"),
                            ("Angiome stellaire", "Angiome stellaire"),
                            ("Anthrax staphylococcique", "Anthrax staphylococcique"),
                            ("Aphtose", "Aphtose"),
                            ("Atrophie", "Atrophie"),
                            ("Balanite", "Balanite"),
                            ("Behçet", "Behçet"),
                            ("Bowen", "Bowen"),
                            ("Carcinome basocellulaire", "Carcinome basocellulaire"),
                            ("Carcinome spinocellulaire", "Carcinome spinocellulaire"),
                            ("Candidose", "Candidose"),
                            ("Chancre mou", "Chancre mou"),
                            ("Couperose", "Couperose"),
                            ("Darier", "Darier"),
                            ("Degos", "Degos"),
                            (
                                "Dermatite actinique chronique",
                                "Dermatite actinique chronique",
                            ),
                            ("Dermatite herpétiforme", "Dermatite herpétiforme"),
                            ("Dermatite atopique", "Dermatite atopique"),
                            ("Dermatophytose", "Dermatophytose"),
                            ("Dermite péri-orale", "Dermite péri-orale"),
                            ("Dermite séborrhéique", "Dermite séborrhéique"),
                            ("Dermographisme", "Dermographisme"),
                            ("Dyshidrose", "Dyshidrose"),
                            ("Eczéma", "Eczéma"),
                            ("Épidermolyse bulleuse", "Épidermolyse bulleuse"),
                            ("Érysipèle", "Érysipèle"),
                            ("Erythema ab igne", "Erythema ab igne"),
                            ("Érythème noueux", "Érythème noueux"),
                            ("Érythème pigmenté fixe", "Érythème pigmenté fixe"),
                            ("Érythème polymorphe", "Érythème polymorphe"),
                            ("Érythrodermie", "Érythrodermie"),
                            ("Erythrasma", "Erythrasma"),
                            ("Escarre", "Escarre"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
    ]
