# Generated by Django 4.2.4 on 2023-08-30 16:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("medecins", "0002_sicks"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sicks",
            name="lst_maladie",
        ),
        migrations.AddField(
            model_name="sicks",
            name="names",
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
