# Generated by Django 4.2.4 on 2023-08-30 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("medecins", "0003_remove_sicks_lst_maladie_sicks_names"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Sicks",
        ),
    ]
