# Generated by Django 4.2 on 2023-08-31 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("medecins", "0004_delete_sicks"),
    ]

    operations = [
        migrations.RenameField(
            model_name="docteurs",
            old_name="comment",
            new_name="Adresse",
        ),
        migrations.RenameField(
            model_name="docteurs",
            old_name="Anneesdepratique",
            new_name="Annees_de_Pratique",
        ),
        migrations.RenameField(
            model_name="docteurs",
            old_name="Certificationsprofessionnelles",
            new_name="Certifications_professionnelles",
        ),
        migrations.RenameField(
            model_name="docteurs",
            old_name="image",
            new_name="Image",
        ),
        migrations.RenameField(
            model_name="docteurs",
            old_name="fullname",
            new_name="Nom_Complete",
        ),
        migrations.RenameField(
            model_name="docteurs",
            old_name="sexe",
            new_name="Sexe",
        ),
        migrations.RenameField(
            model_name="docteurs",
            old_name="specialitesmedicales",
            new_name="Specialites_medicales",
        ),
        migrations.RenameField(
            model_name="docteurs",
            old_name="age",
            new_name="Telephone",
        ),
        migrations.RemoveField(
            model_name="docteurs",
            name="telephone",
        ),
    ]
