# Generated by Django 4.2 on 2023-08-31 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medecins", "0005_rename_comment_docteurs_adresse_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="docteurs",
            name="Telephone",
            field=models.CharField(max_length=20),
        ),
    ]
