# Generated by Django 4.2 on 2023-08-31 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("medecins", "0006_alter_docteurs_telephone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="docteurs",
            name="Telephone",
        ),
    ]
