# Generated by Django 4.2 on 2023-08-31 10:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("medecins", "0007_remove_docteurs_telephone"),
    ]

    operations = [
        migrations.AddField(
            model_name="docteurs",
            name="Telephone",
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
