# Generated by Django 4.2 on 2023-08-31 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("medecins", "0008_docteurs_telephone"),
    ]

    operations = [
        migrations.RenameField(
            model_name="docteurs",
            old_name="Telephone",
            new_name="Telephonee",
        ),
    ]
