# Generated by Django 4.2 on 2023-08-31 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("medecins", "0009_rename_telephone_docteurs_telephonee"),
    ]

    operations = [
        migrations.RenameField(
            model_name="docteurs",
            old_name="Telephonee",
            new_name="telephone",
        ),
    ]
