# Generated by Django 4.2 on 2023-08-31 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("medecins", "0010_rename_telephonee_docteurs_telephone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="docteurs",
            name="telephone",
        ),
    ]
