# Generated by Django 4.2.4 on 2023-08-31 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medecins", "0012_docteurs_telephonee"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="docteurs",
            name="Certifications_professionnelles",
        ),
        migrations.RemoveField(
            model_name="docteurs",
            name="Telephonee",
        ),
        migrations.AlterField(
            model_name="docteurs",
            name="Specialites_medicales",
            field=models.CharField(max_length=200),
        ),
    ]
