# Generated by Django 4.2.4 on 2023-08-31 17:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("medecins", "0013_remove_docteurs_certifications_professionnelles_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="docteurs",
            old_name="Annees_de_Pratique",
            new_name="Anneesdepratique",
        ),
        migrations.RenameField(
            model_name="docteurs",
            old_name="Specialites_medicales",
            new_name="Certificationsprofessionnelles",
        ),
        migrations.RenameField(
            model_name="docteurs",
            old_name="Adresse",
            new_name="comment",
        ),
        migrations.RenameField(
            model_name="docteurs",
            old_name="Nom_Complete",
            new_name="fullname",
        ),
        migrations.RenameField(
            model_name="docteurs",
            old_name="Image",
            new_name="image",
        ),
        migrations.RenameField(
            model_name="docteurs",
            old_name="Sexe",
            new_name="sexe",
        ),
        migrations.AddField(
            model_name="docteurs",
            name="age",
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="docteurs",
            name="specialitesmedicales",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="docteurs",
            name="telephone",
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
