# Generated by Django 4.2.4 on 2023-08-31 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "medecins",
            "0014_rename_annees_de_pratique_docteurs_anneesdepratique_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="Docteurs",
        ),
    ]
