# Generated by Django 4.2.4 on 2023-08-31 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medecins", "0016_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="docteurs",
            name="Certificationsprofessionnelles",
        ),
        migrations.RemoveField(
            model_name="docteurs",
            name="age",
        ),
        migrations.RemoveField(
            model_name="docteurs",
            name="comment",
        ),
        migrations.AlterField(
            model_name="docteurs",
            name="telephone",
            field=models.IntegerField(max_length=30),
        ),
    ]
