# Generated by Django 4.2 on 2023-09-01 13:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("medecins", "0017_remove_docteurs_certificationsprofessionnelles_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="docteurs",
            name="Anneesdepratique",
        ),
        migrations.AddField(
            model_name="docteurs",
            name="adresse",
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
