# Generated by Django 4.2 on 2023-09-04 10:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("medecins", "0019_alter_docteurs_telephone"),
    ]

    operations = [
        migrations.AddField(
            model_name="docteurs",
            name="email",
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
