# Generated by Django 4.2 on 2023-09-04 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("medecins", "0020_docteurs_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="docteurs",
            name="email",
        ),
    ]
