# Generated by Django 4.2 on 2023-09-06 09:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("medecins", "0022_docteursignup"),
    ]

    operations = [
        migrations.AddField(
            model_name="docteurs",
            name="email",
            field=models.EmailField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="docteurs",
            name="fullname",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="docteurs",
            name="specialitesmedicales",
            field=models.CharField(max_length=100),
        ),
    ]
