# Generated by Django 4.2 on 2023-09-14 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecins', '0023_docteurs_email_alter_docteurs_fullname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docteurs',
            name='telephone',
            field=models.CharField(max_length=50),
        ),
    ]
