# Generated by Django 4.2 on 2023-09-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecins', '0025_alter_docteurs_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docteurs',
            name='sexe',
            field=models.CharField(choices=[('H', 'Homme'), ('F', 'Femme')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='docteurs',
            name='telephone',
            field=models.CharField(default='', max_length=50),
        ),
    ]
