# Generated by Django 4.2 on 2023-09-27 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecins', '0026_alter_docteurs_sexe_alter_docteurs_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docteurs',
            name='fullname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='docteurs',
            name='sexe',
            field=models.CharField(choices=[('H', 'Homme'), ('F', 'Femme')], max_length=1),
        ),
        migrations.AlterField(
            model_name='docteurs',
            name='telephone',
            field=models.CharField(max_length=50),
        ),
    ]
