# Generated by Django 4.2.4 on 2023-09-01 18:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0002_patient_sexe_patient_telephone_alter_patient_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="Anneesdepratique",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="Certificationsprofessionnelles",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="admit",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="commnt",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="image",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="specialitesmedicales",
        ),
        migrations.AddField(
            model_name="patient",
            name="symptom",
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="patient",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
